source scripts/color_func.tcl

puts " "
print_blue "prj_dir:            $prj_dir"
print_blue "prj_name:           $prj_name"

puts " "
print_blue "vhdl_rtl_dir:       $vhdl_rtl_dir"
print_blue "vhdl_tb_dir:        $vhdl_tb_dir"
print_blue "ip_blk_srcs:        $ip_blk_srcs"
print_blue "dir_constraint:     $dir_constraint"
print_blue "dir_bin:            $dir_bin"
print_blue "dir_rpt:            $dir_rpt"
print_blue "dir_chkp:           $dir_chkp"
print_blue "dir_logs:           $dir_logs"

puts " "
print_blue "fpga_part_name:     $fpga_part_name"
print_blue "board_part_name:    $board_part_name"
print_blue "top_module_rtl:     $top_module_rtl"

puts " "
print_blue "name_run_rtl:       $name_run_rtl"
print_blue "name_chkp_ip:       $name_chkp_ip"
print_blue "name_chkp_rtl:      $name_chkp_rtl"

puts " "
print_blue "name_run_synth:     $name_run_synth"
print_blue "name_chkp_synth:    $name_chkp_synth"
print_blue "name_rpt_clk:       $name_rpt_clk"
print_blue "name_rpt_timing:    $name_rpt_timing"
print_blue "name_rpt_util:      $name_rpt_util"

puts " "
print_blue "name_run_impl1:     $name_run_impl1"
print_blue "name_chkp_impl1:    $name_chkp_impl1"
print_blue "name_rpt_clk1:      $name_rpt_clk1"
print_blue "name_rpt_timing1:   $name_rpt_timing1"
print_blue "name_rpt_util1:     $name_rpt_util1"

puts " "
print_blue "name_run_impl2:     $name_run_impl2"
print_blue "name_chkp_impl2:    $name_chkp_impl2"
print_blue "name_rpt_clk2:      $name_rpt_clk2"
print_blue "name_rpt_timing2:   $name_rpt_timing2"
print_blue "name_rpt_util2:     $name_rpt_util2"

puts " "
print_blue "name_run_impl3:     $name_run_impl3"
print_blue "name_chkp_impl3:    $name_chkp_impl3"
print_blue "name_rpt_clk3:      $name_rpt_clk3"
print_blue "name_rpt_timing3:   $name_rpt_timing3"
print_blue "name_rpt_util3:     $name_rpt_util3"

puts " "
print_blue "name_run_impl4:     $name_run_impl4"
print_blue "name_chkp_impl4:    $name_chkp_impl4"
print_blue "name_rpt_clk4:      $name_rpt_clk4"
print_blue "name_rpt_timing4:   $name_rpt_timing4"
print_blue "name_rpt_util4:     $name_rpt_util4"

puts " "
print_blue "name_run_impl5:     $name_run_impl5"
print_blue "name_chkp_impl5:    $name_chkp_impl5"
print_blue "name_rpt_clk5:      $name_rpt_clk5"
print_blue "name_rpt_timing5:   $name_rpt_timing5"
print_blue "name_rpt_util5:     $name_rpt_util5"

puts " "
print_blue "name_bitstream:     $name_bitstream"
print_blue "name_run_bit:       $name_run_bit"
print_blue "name_rpt_clk6:      $name_rpt_clk6"
print_blue "name_rpt_timing6:   $name_rpt_timing6"
print_blue "name_rpt_util6:     $name_rpt_util6"
